name: Build and Push OpenProject Docker Image

on:
  push:
    branches:
      - apin/stable-14
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: apinpbsexplorers.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t apinpbsexplorers.azurecr.io/openproject:latest -f docker/prod/Dockerfile

    - name: Push Docker image to ACR
      run: docker push apinpbsexplorers.azurecr.io/openproject:latest
